var annotated_dup =
[
    [ "AlgoritmoDelPintor", "class_algoritmo_del_pintor.html", "class_algoritmo_del_pintor" ],
    [ "ArchivoAIC", "class_archivo_a_i_c.html", "class_archivo_a_i_c" ],
    [ "ArchivoPNM", "class_archivo_p_n_m.html", "class_archivo_p_n_m" ],
    [ "Binarizado", "class_binarizado.html", "class_binarizado" ],
    [ "Brillo", "class_brillo.html", "class_brillo" ],
    [ "Contraste", "class_contraste.html", "class_contraste" ],
    [ "EI_AutoTest", "class_e_i___auto_test.html", "class_e_i___auto_test" ],
    [ "EspacioDeTrabajo", "class_espacio_de_trabajo.html", "class_espacio_de_trabajo" ],
    [ "ExcepcionArchivoCorrupto", "class_excepcion_archivo_corrupto.html", "class_excepcion_archivo_corrupto" ],
    [ "ExcepcionArchivoNoSoportado", "class_excepcion_archivo_no_soportado.html", "class_excepcion_archivo_no_soportado" ],
    [ "FiltroMediana", "class_filtro_mediana.html", "class_filtro_mediana" ],
    [ "FiltroPasaAltos", "class_filtro_pasa_altos.html", "class_filtro_pasa_altos" ],
    [ "FiltroPasaBajos", "class_filtro_pasa_bajos.html", "class_filtro_pasa_bajos" ],
    [ "GestorDeArchivo", "class_gestor_de_archivo.html", "class_gestor_de_archivo" ],
    [ "GraficadorHistograma", "class_graficador_histograma.html", "class_graficador_histograma" ],
    [ "Imagen", "class_imagen.html", "class_imagen" ],
    [ "LUT", "class_l_u_t.html", "class_l_u_t" ],
    [ "Negativo", "class_negativo.html", "class_negativo" ],
    [ "Pixel", "class_pixel.html", "class_pixel" ],
    [ "ProcesadorDeImagen", "class_procesador_de_imagen.html", "class_procesador_de_imagen" ],
    [ "ProcesadorEstadistico", "class_procesador_estadistico.html", "class_procesador_estadistico" ],
    [ "QObject", "class_q_object.html", null ],
    [ "QOpenGLFunctions", "class_q_open_g_l_functions.html", null ],
    [ "QOpenGLWidget", "class_q_open_g_l_widget.html", null ],
    [ "qt_meta_stringdata_VentanaDeGraficacion_t", "structqt__meta__stringdata___ventana_de_graficacion__t.html", "structqt__meta__stringdata___ventana_de_graficacion__t" ],
    [ "Sistema", "class_sistema.html", "class_sistema" ],
    [ "VentanaDeGraficacion", "class_ventana_de_graficacion.html", "class_ventana_de_graficacion" ]
];